#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: false
        default: "false"

env:
  REPO_URL: https://github.com/openwrt/openwrt.git
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  FUNCS_SH: funcs.sh
  CORRECT_VERMAGIC: correct-vermagic.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: false
  UPLOAD_WETRANSFER: false
  UPLOAD_OSHI: false
  UPLOAD_TRANSFER: true  
  UPLOAD_RELEASE: false
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install tmate
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

      - name: Load custom feeds
        run: |
          chmod +x $DIY_P1_SH $FUNCS_SH


      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}



      - name: Compile the firmware
        id: compile
        run: |
          cd /workdir
          ls -l /workdir
          dd if=/dev/zero of=test.img bs=1M count=5
          ls -l `pwd`


      - name: Upload firmware to transfer.sh
        id: transfer
        run: |
          cd /workdir
          logfile=transfer.log
          $GITHUB_WORKSPACE/$FUNCS_SH progress transfer.log &
          ps aux|grep funcs.sh
          ls -l
          curl --upload-file test.img https://transfer.sh/test.img -o url.log 2>transfer.log
          ps aux|grep curl
          cat $logfile
          echo "+++++++++++++++++++++++++++++++++++++++++++++++++++"
          cat url.log
          echo "url=$(cat url.log)" >> $GITHUB_OUTPUT
          ls -l

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3


